namespace NexaFlow.Domain.Common;

/// <summary>
///     Base class for all domain entities. Holds the identity and a collection
///     of domain events that were raised during the current unit of work.
///     <para>
///         Identity uses a sequential Guid (host responsibility — generated by EF Core
///         when not provided by the domain). Equality is based on the Id, not on reference.
///     </para>
///     <para>
///         Invariants are protected by private setters and explicit domain methods
///         (section 10 — avoid public setters everywhere).
///     </para>
/// </summary>
public abstract class Entity : IEquatable<Entity>
{
    private readonly List<IDomainEvent> _domainEvents = [];

    /// <summary>Stable identity for this entity.</summary>
    public Guid Id { get; protected set; } = Guid.NewGuid();

    /// <summary>
    ///     Domain events queued for dispatch by the Application layer after SaveChanges.
    ///     Cleared by the dispatcher after handling.
    /// </summary>
    public IReadOnlyList<IDomainEvent> DomainEvents => _domainEvents.AsReadOnly();

    /// <summary>
    ///     Queue a domain event to be dispatched on successful persistence.
    ///     <para>
    ///         Visibility is <c>internal</c> — visible to Application via
    ///         <c>InternalsVisibleTo</c>. Keeps the queue accessible without exposing it
    ///         to consumers that shouldn't be raising events directly (e.g., the API host).
    ///     </para>
    /// </summary>
    internal void AddDomainEvent(IDomainEvent @event)
    {
        ArgumentNullException.ThrowIfNull(@event);
        _domainEvents.Add(@event);
    }

    /// <summary>
    ///     Drain the queued events. Called by the dispatcher (Phase 6+) once events are
    ///     published to the outbox / message broker. Not called in Phase 1.
    /// </summary>
    public void ClearDomainEvents() => _domainEvents.Clear();

    public bool Equals(Entity? other)
    {
        if (other is null) return false;
        if (ReferenceEquals(this, other)) return true;
        if (GetType() != other.GetType()) return false;
        return Id == other.Id;
    }

    public override bool Equals(object? obj) => Equals(obj as Entity);

    public override int GetHashCode() => Id.GetHashCode();

    public static bool operator ==(Entity? left, Entity? right) => Equals(left, right);

    public static bool operator !=(Entity? left, Entity? right) => !Equals(left, right);
}
